---
driver_plugin: vagrant
provisioner: chef_zero

platforms:
- name: centos-6.4_chef-11.6.0
  driver_config:
    box: opscode-centos-6.4_chef-11.6.0
    box_url:  https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.4_chef-11.6.0.box

- name: ubuntu-12.04_chef-11.4.4
  run_list:
    - recipe[ubuntu]
  driver_config:
    box: opscode-ubuntu-12.04_chef-11.4.4
    box_url:  https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_chef-11.4.4.box

suites:
- name: default
  run_list:
    - recipe[bind::master]
  attributes:
    dns:
      master: 10.0.2.15
      zones:
        - test
